spring.application.name=


server.port=9009

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=System
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.jackson.mapper.sort-properties-alphabetically=false
